blank_issues_enabled: false
contact_links:
  - name: Mozilla Connect
    url: https://connect.mozilla.org/t5/ideas/idb-p/ideas/label-name/thunderbird%20android
    about: Sumbit your ideas for improving Thunderbird for Android. 
