---
name: Close old issues with the needinfo label

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Close old issues with the needinfo tag
        uses: dwieeb/needs-reply@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-label: "status: needs information"
          days-before-close: 30
          close-message: >
            Thank you for taking the time to report this issue. It looks like we haven't heard back
            in a while, therefore we're closing this issue. If the problem persists in the latest
            version please open a new issue and reference this one so we can follow up more
            effectively.
