---
name: Remove needinfo label

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      github.event.comment.author_association != 'OWNER' &&
      github.event.comment.author_association != 'MEMBER' &&
      github.event.comment.author_association != 'COLLABORATOR'
    permissions:
      issues: write
      pull-requests: write
    steps:
      # https://github.com/octokit/request-action/issues/118
      - name: Remove needinfo label
        run: |
          curl --request DELETE \
            --url 'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/status%3A%20needs%20information' \
            --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
